### PR TITLE
Update for iOS 9 and Safari 9 compatibility

### PR DESCRIPTION
**Pull request by ltullman**
Add workaround for isArray check failing due to Arguments not being recognized as an Array in Safari 9.

### CODE REVIEW

**Comment by mmikowski** [comment]
Hi Ltullman:

Thanks for your work!

I have incorporated this change, as well as regression tests (!) and jslint fixes in this branch: `https://github.com/mmikowski/taffydb`. Please check it out :)

I added rudimentary regression tests, but they are easy to expand and port to run headless on node.js (see `taffy-test.html`)

We should look at forking this project if Ian cannot be found.  I'm willing to guide the project and even asked him if I could take over, but haven't heard back from him.

It would be sad to fork, but even worse if we couldn't keep using this software.  A few thoughts if we went that way:

- We would need a new name that is sticky and evokes memories of taffydb
- We should see if we could get Ian to point others to the new project, or (again, better yet) just transfer TaffyDB to new management 
- We definitely want to compare to existing projects to see if something better or redundant has come along

Cheers, Mike

**Comment by ltullman** [comment]
Hi Mike, You're welcome and I agree about this project needing a maintainer again.  I sent Ian a tweet so hoping he replies.

**Comment by mmikowski** [comment]
Same here.  Thanks for your help.  It fixed our iOS9 bug for our VP and CEO.  Very helpful!

**Comment by LucasLazaro** [comment]
Apparently I'm facing a similar problem, when `inserting` entries to a DB it does not persist. Trying to retrieve gives me an empty array or simply `db().count() = 0`. 

@ltullman Was your fix intended to fix this issue?

**Comment by ltullman** [comment]
@LucasLazaro Yeah, it should solve that.

**Comment by typicaljoe** [comment]
Are you guys willing to merge these changes into the base branch?

**Comment by mmikowski** [comment]
This looks good to me.  I tested here.  iOS9 now works, and regression tests pass.

**Pull request merged**
